scalafiddle:
  dependency: org.typelevel %%% cats-mtl-core % 0.4.0,io.circe %%% circe-core % 0.8.0,io.circe %%% circe-generic % 0.8.0,io.circe %%% circe-parser % 0.8.0
  scalaFiddleUrl: https://wibisono.github.io/fp-oops/
